routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use TCG\Voyager\Facades\Voyager;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\Voyager\ParticipantController;
use App\Http\Controllers\ExportController;
use App\Http\Controllers\ChildrenController;
//use App\Http\Controllers\Voyager\VoyagerSettingsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group([
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function() {
        Route::get('/', [PageController::class,'index'])->name('index');
        Route::get('/about-us', [PageController::class,'about'])->name('about');
        Route::get('/release', [PageController::class,'release'])->name('release');
        Route::resource('/posts', PostController::class)
            ->only(['index', 'show'])
            ->names('posts');
        Route::resource('/events', EventController::class)
            ->only(['index', 'show'])
            ->names('events');
        Route::post('/add-message', [MessageController::class, 'addMessage'])
            ->name('addMessage');
});

Route::post('/event-participate/{event}', [EventController::class, 'onParticipate'])->middleware('auth')->name('eventParticipate');

// Panel pages
Route::group(['prefix' => 'panel'], function () {
    Voyager::routes();
    Route::get('/events/{event}/participants',[ParticipantController::class,'indexByEvent'])->name('voyager.participants.indexByEvent');
    Route::get('/to-accept-participant/{participant}',[ParticipantController::class,'toAccept'])->name('voyager.participants.toAccept');
    Route::get('/to-reject-participant/{participant}',[ParticipantController::class,'toReject'])->name('voyager.participants.toReject');
    Route::get('/to-draft-participant/{participant}',[ParticipantController::class,'toDraft'])->name('voyager.participants.toDraft');
    Route::get('/to-invite-participant/{participant}',[ParticipantController::class,'toInvite'])->name('voyager.participants.toInvite');
    Route::post('/to-invite-participant-bulk/{event}',[ParticipantController::class,'toInviteBulk'])->name('voyager.participants.toInviteBulk');
    Route::get('/to-service-participant/{participant}',[ParticipantController::class,'toService'])->name('voyager.participants.toService');

    Route::get('/events/{event}/participants/export/', [ExportController::class, 'exportParticipantsEvent'])->name('export.participants.event');
});

// Profile pages
Route::get('/dashboard', [ProfileController::class, 'show'])->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::patch('/update-contact-info', [ProfileController::class, 'updateContactInfo'])->name('profile.updateContactInfo');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('/children', ChildrenController::class)->only(['index','store']);
    Route::patch('/children/{children}', [ChildrenController::class, 'update'])->name('children.update');
    Route::delete('/children/{children}', [ChildrenController::class, 'destroy'])->name('children.destroy');

});

require __DIR__.'/auth.php';

app/Models/Children.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Laravel\Sanctum\HasApiTokens;

class Children extends Model
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    protected $table = 'children';
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'document_type',
        'document',
        'gender',
        'birthday',
    ];

    protected $dates = ['deleted_at'];

    public function save(array $options = [])
    {
        if (!$this->created_by && Auth::user()) {
            $this->created_by = Auth::user()->id;
        }

        if (Auth::user()) {
            $this->updated_by = Auth::user()->id;
        }

        return parent::save();
    }

    public function parents()
    {
        return $this->belongsToMany(User::class, 'user_children', 'children_id', 'user_id');
    }

    public function getFullNameAttribute() {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }

    public function getAgeAttribute() {
        $dob = new \DateTime($this->birthday);
        $now = new \DateTime();
        $diff = $now->diff($dob);
        return $diff->y;
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="mt-6">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
    <div class="max-w-7xl py-6 flex mx-auto">
        <div class=" sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <section>
                        <header>
                            <h2 class="text-lg font-medium text-gray-900 mb-2">Participation in events</h2>
                            <hr>
                            @foreach($events as $event)
                                <p class="mt-1">
                                    {{ $event->title }}
                                </p>
                                <p class="mt-1 text-sm text-gray-600">
                                    <b>Event start:</b> {{ $event->event_start }}<br>
                                    <b>Event end:</b> {{ $event->event_end }}
                                </p>
                                <p class="mt-1 mb-1 text-sm text-gray-600">
                                    <b>Status:</b> {{ $event->pivot->status }}
                                </p>
                                <hr>
                            @endforeach
                        </header>
                    </section>
                </div>
            </div>
        </div>
        <div class="sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <section>
                        <header>
                            <h2 class="text-lg font-medium text-gray-900">Children</h2>
                            @foreach($children as $child)
                                <p class="mt-1">
                                    <b>Full name: </b>{{ $child->full_name }}<br>
                                    <b>Birthday: </b>{{ $child->birthday }}

                                </p>
                                <hr>
                            @endforeach
                        </header>
                    </section>
                </div>
            </div>
        </div>
        <div class="sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <section>
                        <header>
                            <h2 class="text-lg font-medium text-gray-900">Additional Information</h2>
                            <p class="mt-1 text-sm text-gray-600">Later...</p>
                        </header>
                    </section>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/index.blade.php
@extends('layouts.application')

@section('title','Home')
@section('og:description', env('APP_DEMO') ? __('demo.our_mission_text') : __('custom.our_mission_text'))

@section('content')
    @include('partial.main-slider')
    @include('partial.welcome-section')
    @include('partial.our-story-block')
    @if(!env('APP_DEMO'))
        @include('partial.ad-block')
    @endif
    @if(env('APP_DEMO'))
        @include('partial.demo.person-block-demo')
    @else
        @include('partial.person-block')
    @endif
{{--    @include('partial.call-to-action')--}}
    @include('partial.upcoming-events-block')
{{--    @include('partial.volunteer-reg-form')--}}
{{--    @include('partial.latest-news-block')--}}
{{--    @include('partial.testimonial-block')--}}
    @include('partial.contact-block')

@endsection