routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use TCG\Voyager\Facades\Voyager;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\Voyager\ParticipantController;
use App\Http\Controllers\ExportController;
use App\Http\Controllers\ChildrenController;
//use App\Http\Controllers\Voyager\VoyagerSettingsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group([
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function() {
        Route::get('/', [PageController::class,'index'])->name('index');
        Route::get('/about-us', [PageController::class,'about'])->name('about');
        Route::get('/release', [PageController::class,'release'])->name('release');
        Route::resource('/posts', PostController::class)
            ->only(['index', 'show'])
            ->names('posts');
        Route::resource('/events', EventController::class)
            ->only(['index', 'show'])
            ->names('events');
        Route::post('/add-message', [MessageController::class, 'addMessage'])
            ->name('addMessage');
});

Route::post('/event-participate/{event}', [EventController::class, 'onParticipate'])->middleware('auth')->name('eventParticipate');

// Panel pages
Route::group(['prefix' => 'panel'], function () {
    Voyager::routes();
    Route::get('/events/{event}/participants',[ParticipantController::class,'indexByEvent'])->name('voyager.participants.indexByEvent');
    Route::get('/to-accept-participant/{participant}',[ParticipantController::class,'toAccept'])->name('voyager.participants.toAccept');
    Route::get('/to-reject-participant/{participant}',[ParticipantController::class,'toReject'])->name('voyager.participants.toReject');
    Route::get('/to-draft-participant/{participant}',[ParticipantController::class,'toDraft'])->name('voyager.participants.toDraft');
    Route::get('/to-invite-participant/{participant}',[ParticipantController::class,'toInvite'])->name('voyager.participants.toInvite');
    Route::post('/to-invite-participant-bulk/{event}',[ParticipantController::class,'toInviteBulk'])->name('voyager.participants.toInviteBulk');
    Route::get('/to-service-participant/{participant}',[ParticipantController::class,'toService'])->name('voyager.participants.toService');

    Route::get('/events/{event}/participants/export/', [ExportController::class, 'exportParticipantsEvent'])->name('export.participants.event');
});

// Profile pages
Route::get('/dashboard', [ProfileController::class, 'show'])->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::patch('/update-contact-info', [ProfileController::class, 'updateContactInfo'])->name('profile.updateContactInfo');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('/children', ChildrenController::class)->only(['index','store']);
    Route::patch('/children/{children}', [ChildrenController::class, 'update'])->name('children.update');
    Route::delete('/children/{children}', [ChildrenController::class, 'destroy'])->name('children.destroy');

});

require __DIR__.'/auth.php';

app/Models/Children.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Laravel\Sanctum\HasApiTokens;

class Children extends Model
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    protected $table = 'children';
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'document_type',
        'document',
        'gender',
        'birthday',
    ];

    protected $dates = ['deleted_at'];

    public function save(array $options = [])
    {
        if (!$this->created_by && Auth::user()) {
            $this->created_by = Auth::user()->id;
        }

        if (Auth::user()) {
            $this->updated_by = Auth::user()->id;
        }

        return parent::save();
    }

    public function parents()
    {
        return $this->belongsToMany(User::class, 'user_children', 'children_id', 'user_id');
    }

    public function getFullNameAttribute() {
        return ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
    }

    public function getAgeAttribute() {
        $dob = new \DateTime($this->birthday);
        $now = new \DateTime();
        $diff = $now->diff($dob);
        return $diff->y;
    }
}

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use TCG\Voyager\Traits\Translatable;

class Event extends Model
{
    use HasFactory;
    use Translatable;
    protected $translatable = [
        'title',
        'excerpt',
        'description',
    ];

    public function save(array $options = [])
    {
        // If no author has been assigned, assign the current user's id as the author of the post
        if (!$this->author_id && Auth::user()) {
            $this->author_id = Auth::user()->id;
        }

        if (!$this->created_by && Auth::user()) {
            $this->created_by = Auth::user()->id;
        }

        if (Auth::user()) {
            $this->updated_by = Auth::user()->id;
        }

        return parent::save();
    }

    public function delete(): bool
    {
        if(parent::delete()) {
            $this->participations()->detach();
        }

        return true;
    }

    public function scopePublished($query)
    {
        return $query->whereIn('status', ['published','finished','registration']);
    }

    public function participations()
    {
        return $this->belongsToMany(User::class,'participants', 'event_id', 'user_id');
    }

    public function isParticipant(User $user): bool
    {
        return $this->participations()->get()->contains($user);
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Enums\ParticipantStatusEnum;
use App\Models\Event;
use App\Models\Participant;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class EventController extends Controller
{
    public function index()
    {
        return view('events.index')->with([
            'events' => Event::withTranslations()->published()->simplePaginate(4),
            'recentEvents'=>Event::orderBy('id','desc')->published()->take(3)->withTranslations()->get()
        ]);
    }

    public function show(Event $event)
    {
        if(!in_array($event->status, ['PUBLISHED','FINISHED','REGISTRATION'])) {
            abort(403);
        }

        return view('events.show')->with([
            'event' => $event,
            'partCurrentEvent' => Participant::where(['user_id' => Auth::id(), 'event_id' => $event->id])->first(),
            'recentEvents'=>Event::orderBy('id','desc')->published()->take(3)->withTranslations()->get()
        ]);
    }

    public function onParticipate(Event $event, Request $request)
    {
        //TODO: Make custom request
        $data = $request->all();
        $user = User::find($data['user_id']);
//        if($event->isParticipant($user)) {
//            return redirect()->back()->with('warning','You are already participating in the event!');
//        }

        if($event->max_part && count($event->participations) >= $event->max_part) {
            $event->status = 'PUBLISHED';
            $event->save();

            return redirect()->back()->with('warning','Registration for the event is closed!');
        }

        $partDate =  [
            'status' => ParticipantStatusEnum::DRAFT(),
            'created_by' => $user->id,
            'created_at' => date('Y-m-d H:i:s', time()),
            'updated_by' => $user->id,
            'updated_at' => date('Y-m-d H:i:s', time()),
            'users' => []
        ];

        if(isset($data['selected-me'])) {
            $partDate['users']['user'] = $data['selected-me'];
        }
        if(isset($data['selected-children'])) {
            $partDate['users']['children'] = $data['selected-children'];
        }

        $event->participations()->detach($user->id);

        if(!empty($partDate['users'])) {
            $partDate['users'] = json_encode($partDate['users']);
            $event->participations()->attach($user->id, $partDate);
        }

        return redirect()->back()->with('success','Your request has been submitted. Admin check it out!');
    }
}

resources/views/events/index.blade.php
@extends('layouts.application')

@section('title','Events')
@section('og:image', '/template/images/logo.png')
@section('og:description', env('APP_DEMO') ? __('demo.our_mission_text') : __('custom.our_mission_text'))

@section('content')

    @include('partial.events-block')
    @include('partial.contact-block')

@endsection

resources/views/events/show.blade.php
@extends('layouts.application')

@section('title', $event->getTranslatedAttribute('title', App::getLocale(), 'fallbackLocale'))
@section('og:image', Voyager::image($event->image))
@section('og:description', $event->excerpt)

@section('content')
    <section class="news-detail-header-section text-center">
        <div class="section-overlay"></div>

        <div class="container">
            <div class="row">

                <div class="col-lg-12 col-12">
                    <h1 class="text-white">{{ __('custom.event_details') }}</h1>
                </div>

            </div>
        </div>
    </section>

    <section class="news-section section-padding">
        <div class="container">
            <div class="row">

                <div class="col-lg-7 col-12">
                    <div class="news-block">
                        <div class="news-block-top">
                            @if($event->image)
                                <img src="{{ Voyager::image($event->image) }}" class="news-image img-fluid" alt="">
                            @else
                                <img src="{{ asset('/template/images/news/medium-shot-volunteers-with-clothing-donations.jpg') }}" class="news-image img-fluid" alt="">
                            @endif
                        </div>

                        <div class="news-block-info">
                            <div class="d-flex mt-2">
                                <div class="news-block-date">
                                    <p>
                                        <i class="bi-calendar4 custom-icon me-1"></i>
                                        {{ $event->event_start }}
                                        @if($event->event_end)
                                        /
                                        <i class="bi-calendar4 custom-icon me-1"></i>
                                        {{ $event->event_end }}
                                        @endif
                                    </p>
                                </div>
                            </div>
                            @if($event->age_from || $event->age_to)
                                <div class="d-flex mt-2">
                                    <div class="news-block-date">
                                        <p>
                                            <strong>{{ __('custom.age_restrictions') }}:</strong>
                                            {{ $event->age_from . ' - ' }}{{ $event->age_to }}
                                        </p>
                                    </div>
                                </div>
                            @endif

                            <div class="news-block-title mb-2">
                                <h4>{{ $event->getTranslatedAttribute('title', App::getLocale(), 'fallbackLocale') }}</h4>
                            </div>

                            <div class="news-block-body">
                                {!! $event->getTranslatedAttribute('description', App::getLocale(), 'fallbackLocale') !!}
                            </div>

                            {{--                            <div class="social-share border-top mt-5 py-4 d-flex flex-wrap align-items-center">--}}

                            {{--                            </div>--}}

                        </div>
                    </div>
                    @if($event->status === 'REGISTRATION' and $event->use_registration)
                        @php($showRegisterButton = false)
                        @include('layouts.alert')
                        @if(!Auth::check())
                           <button id="send-part-form" type="submit" class="form-control mt-4">
                                <a href="{{ route('register') }}" target="_blank">{{ __('custom.login') }}</a>
                            </button>
                        @else
                            <hr>
                            <form class="custom-form col-lg-8 col-8 offset-2" action="{{ route('eventParticipate', $event) }}"
                          method="post" role="form">
                        {{ csrf_field() }}
                        <input type="hidden" value="{{ $event->id }}" name="event_id">
                        <input type="hidden" value="{{ Auth::id() }}" name="user_id">

                        @if((!$event->age_from and !$event->age_to) or $event->age_from >= 18 )
                        <label>
                            <input type="checkbox" @if($partCurrentEvent) disabled @endif name="selected-me"
                                   class="select-participant"
                                   @if(!empty($partCurrentEvent->users['user']) && $partCurrentEvent->users['user'] == Auth::id()) checked @endif
                                   value="{{ \Illuminate\Support\Facades\Auth::id() }}">
                            {{ __('custom.me') }}
                        </label>
                        <br>
                            @php($showRegisterButton = true)
                        @endif
                        @foreach(Auth::user()->children as $child)
                            @if((!$event->age_from || $child->age >= $event->age_from)
                                    && (!$event->age_to || $child->age <= $event->age_to))
                                        <label>
                                            <input type="checkbox" @if($partCurrentEvent) disabled @endif
                                            name="selected-children[]" class="select-participant" value="{{ $child->id }}"
                                            @if(isset($partCurrentEvent->users['children']) && in_array($child->id, $partCurrentEvent->users['children'])) checked @endif>
                                            {{ $child->full_name }}
                                        </label>
                                        <br>
                                        @php($showRegisterButton = true)
                            @endif
                        @endforeach
                        @if($showRegisterButton)
                            <button id="send-part-form" type="submit" @if($partCurrentEvent) disabled @endif class="form-control mt-4">
                                {{ __('custom.register') }}
                            </button>
                        @endif

                        </form>
                        @endif
                        @if($partCurrentEvent)
                            <p class="text-center">
                                {{ __('custom.you_already_registered') }} <br> {{ __('custom.your_status') }} - {{ $partCurrentEvent->status }} <br>
                                {!! __('custom.change_choice') !!}
                            </p>
                        @endif
                    @elseif($event->status === 'FINISHED')
                        <h5 class="text-center">
                            {{ __('custom.event_finished') }}
                        </h5>
                    @elseif($event->status === 'PUBLISHED' and $event->use_registration)
                        @if($partCurrentEvent)
                            <p class="text-center">
                                {{ __('custom.you_already_registered') }} <br> {{ __('custom.your_status') }} - {{ $partCurrentEvent->status }} <br>
                            </p>
                        @endif
                    @endif
                    <hr>
                    <div class="fb-share-button"
                         data-href="{{ env('APP_ENV') == 'local' ? 'https://www.hadas.am-saved.info/ru/about-us' : Request::url() }}"
                         data-layout="button_count">
                    </div>
                </div>

                <div class="col-lg-4 col-12 mx-auto mt-4 mt-lg-0">
                    @include('partial.recent-posts')
                </div>

            </div>
        </div>
    </section>
@endsection
<script>
        document.addEventListener('click', function (event) {
            if (!event.target.matches('#change-choice')) return;

            event.preventDefault();
            const boxes = document.querySelectorAll('.select-participant');
            boxes.forEach((element) => {
                element.removeAttribute('disabled')
            })
            document.getElementById('send-part-form').removeAttribute('disabled')
        }, false);
</script>