routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use TCG\Voyager\Facades\Voyager;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\Voyager\ParticipantController;
use App\Http\Controllers\ExportController;
use App\Http\Controllers\ChildrenController;
//use App\Http\Controllers\Voyager\VoyagerSettingsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group([
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function() {
        Route::get('/', [PageController::class,'index'])->name('index');
        Route::get('/about-us', [PageController::class,'about'])->name('about');
        Route::get('/release', [PageController::class,'release'])->name('release');
        Route::resource('/posts', PostController::class)
            ->only(['index', 'show'])
            ->names('posts');
        Route::resource('/events', EventController::class)
            ->only(['index', 'show'])
            ->names('events');
        Route::post('/add-message', [MessageController::class, 'addMessage'])
            ->name('addMessage');
});

Route::post('/event-participate/{event}', [EventController::class, 'onParticipate'])->middleware('auth')->name('eventParticipate');

// Panel pages
Route::group(['prefix' => 'panel'], function () {
    Voyager::routes();
    Route::get('/events/{event}/participants',[ParticipantController::class,'indexByEvent'])->name('voyager.participants.indexByEvent');
    Route::get('/to-accept-participant/{participant}',[ParticipantController::class,'toAccept'])->name('voyager.participants.toAccept');
    Route::get('/to-reject-participant/{participant}',[ParticipantController::class,'toReject'])->name('voyager.participants.toReject');
    Route::get('/to-draft-participant/{participant}',[ParticipantController::class,'toDraft'])->name('voyager.participants.toDraft');
    Route::get('/to-invite-participant/{participant}',[ParticipantController::class,'toInvite'])->name('voyager.participants.toInvite');
    Route::post('/to-invite-participant-bulk/{event}',[ParticipantController::class,'toInviteBulk'])->name('voyager.participants.toInviteBulk');
    Route::get('/to-service-participant/{participant}',[ParticipantController::class,'toService'])->name('voyager.participants.toService');

    Route::get('/events/{event}/participants/export/', [ExportController::class, 'exportParticipantsEvent'])->name('export.participants.event');
});

// Profile pages
Route::get('/dashboard', [ProfileController::class, 'show'])->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::patch('/update-contact-info', [ProfileController::class, 'updateContactInfo'])->name('profile.updateContactInfo');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('/children', ChildrenController::class)->only(['index','store']);
    Route::patch('/children/{children}', [ChildrenController::class, 'update'])->name('children.update');
    Route::delete('/children/{children}', [ChildrenController::class, 'destroy'])->name('children.destroy');

});

require __DIR__.'/auth.php';

resources/views/partial/ad-block.blade.php
<section class="volunteer-section section-padding">
    <div class="container">
        <div class="row">

            <div class="col-lg-8 col-md-8 col-12">
                <p>
                    <video class="video-block" controls="controls">
                        <source src="https://armiyatanaspasenieto.org/video/family_meet.mp4" type="video/mp4">
                    </video>
                </p>
            </div>

            <div class="col-lg-4 col-md-4 col-12">
                <div class="custom-text-block">
                    <h2 class="text-white mb-0">{{ \App\Models\SettingTranslation::getTranslation('ad-block.title', App::getLocale()) }}</h2>
                    <p class="text-white mb-lg-4 mb-md-4">{{ \App\Models\SettingTranslation::getTranslation('ad-block.subtitle', App::getLocale()) }}</p>
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/partial/contact-block.blade.php
<section class="contact-section section-padding" id="section_6">
    <div class="container">
        <div class="row">

            <div class="col-lg-4 col-12 ms-auto mb-5 mb-lg-0">
                <div class="contact-info-wrap">
                    <h2>{{ __('custom.get_in_touch') }}</h2>

                    <div class="contact-image-wrap d-flex flex-wrap">
{{--                        @if(setting('personblock.image'))--}}
{{--                            <img src="{{ Voyager::image(setting('personblock.image')) }}" class="img-fluid avatar-image" alt="">--}}
{{--                        @else--}}
{{--                            <img src="{{ asset('/template/images/portrait-volunteer-who-organized-donations-charity.jpg') }}" class="img-fluid avatar-image" alt="">--}}
{{--                        @endif--}}

                        <div class="d-flex flex-column justify-content-center ms-3">
{{--                            <p class="mb-0">{{ \App\Models\SettingTranslation::getTranslation('personblock.title2', App::getLocale()) }}</p>--}}
{{--                            <p class="mb-0"><strong>{{ \App\Models\SettingTranslation::getTranslation('personblock.sub_title2', App::getLocale()) }}</strong></p>--}}
                            <p class="mb-0">{{ trans('settings.personblock.worktime') }}</p>
                            <p class="mb-0"><i class="bi-telephone me-2"></i> {{ setting('contacts.phone_2') }}</p>
{{--                            <p class="mb-0"><i class="bi-envelope me-2"></i> {{ setting('contacts.email_2') }}</p>--}}
                        </div>
                    </div>

                    <div class="contact-info">
                        <h5 class="mb-3">{{ __('custom.contact_information') }}</h5>

                        <p class="d-flex mb-2">
                            <i class="bi-geo-alt me-2"></i>
                            {{ setting('contacts.address_1') }}
                        </p>

                        <p class="d-flex mb-2">
                            <i class="bi-telephone me-2"></i>

                            <a href="tel: 120-240-9600">
                                {{ setting('contacts.phone_1') }}
                            </a>
                        </p>

                        <p class="d-flex">
                            <i class="bi-envelope me-2"></i>

                            <a href="mailto:{{ setting('contacts.email_1') }}">
                                {{ setting('contacts.email_1') }}
                            </a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-lg-5 col-12 mx-auto">
                <form class="custom-form contact-form" action="{{ route('addMessage') }}"
                enctype="multipart/form-data" method="post" role="form">
                @csrf

                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-12">
                            <input type="text" name="name" id="first-name" class="form-control" placeholder="{{ __('custom.name') }}" required>
                        </div>

                        <div class="col-lg-6 col-md-6 col-12">
                            <input type="text" name="surname" id="last-name" class="form-control" placeholder="{{ __('custom.surname') }}" required>
                        </div>
                    </div>
                    <input type="email" name="email" id="email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="{{ __('custom.email') }}" required>
                    <textarea name="message" rows="5" class="form-control" id="message" placeholder="{{ __('custom.who_help') }}"></textarea>

                    <button type="submit" class="form-control">{{ __('custom.send_message') }}</button>
                </form>
            </div>

        </div>
    </div>
</section>

resources/views/partial/events-block.blade.php
<section class="news-section section-padding">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12 mb-5">
                <h2>{{ __('custom.events') }}</h2>
            </div>

            <div class="col-lg-7 col-12">
                @if(count($events) > 0)
                    @foreach($events as $event)
                        <div class="news-block mb-1">
                            <div class="news-block-top">
                                <a href="{{ route('events.show', $event) }}">
                                    @if($event->image)
                                        <img src="{{ Voyager::image($event->image) }}" class="news-image img-fluid" alt="">
                                    @else
                                        <img src="{{ asset('/template/images/news/medium-shot-volunteers-with-clothing-donations.jpg') }}" class="news-image img-fluid" alt="">
                                    @endif
                                </a>
                            </div>

                            <div class="news-block-info">
                                <div class="d-flex mt-2">
                                    <div class="news-block-date">
                                        <p>
                                            <i class="bi-calendar4 custom-icon me-1"></i>
                                            {{ $event->event_start }}
                                        /
                                            <i class="bi-calendar4 custom-icon me-1"></i>
                                            {{ $event->event_end }}
                                        </p>
                                    </div>
                                </div>

                                <div class="news-block-title mb-2">
                                    <h4>
                                        <a href="{{ route('events.show', $event) }}" class="news-block-title-link">
                                            {{ $event->getTranslatedAttribute('title', App::getLocale(), 'fallbackLocale') }}
                                        </a>
                                    </h4>
                                </div>

                                <div class="news-block-body">
                                    <p>{{ $event->getTranslatedAttribute('excerpt', App::getLocale(), 'fallbackLocale')}}</p>
                                </div>
                            </div>
                        </div>
                    @endforeach
                        <div class="text-center">{{ $events->links() }}</div>
                @else
                    {{ __('custom.not_found_active_events') }}
                @endif
            </div>

            <div class="col-lg-4 col-12 mx-auto">

               @include('partial.recent-posts')

{{--                <div class="category-block d-flex flex-column">--}}
{{--                    <h5 class="mb-3">{{ trans_choice('custom.category',2) }}</h5>--}}

{{--                    <a href="#" class="category-block-link">--}}
{{--                        Drinking water--}}
{{--                        <span class="badge">20</span>--}}
{{--                    </a>--}}

{{--                    <a href="#" class="category-block-link">--}}
{{--                        Food Donation--}}
{{--                        <span class="badge">30</span>--}}
{{--                    </a>--}}

{{--                    <a href="#" class="category-block-link">--}}
{{--                        Children Education--}}
{{--                        <span class="badge">10</span>--}}
{{--                    </a>--}}

{{--                    <a href="#" class="category-block-link">--}}
{{--                        Poverty Development--}}
{{--                        <span class="badge">15</span>--}}
{{--                    </a>--}}

{{--                    <a href="#" class="category-block-link">--}}
{{--                        Clothing Donation--}}
{{--                        <span class="badge">20</span>--}}
{{--                    </a>--}}
{{--                </div>--}}

            </div>

        </div>
    </div>
</section>

resources/views/partial/latest-news-block.blade.php
<section class="news-section section-padding" id="section_5">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12 mb-5">
                <h2>Latest News</h2>
            </div>

            <div class="col-lg-7 col-12">
                <div class="news-block">
                    <div class="news-block-top">
                        <a href="news-detail.html">
                            <img src="{{ Vite::asset('resources/images/news/medium-shot-volunteers-with-clothing-donations.jpg') }}" class="news-image img-fluid" alt="">
                        </a>

                        <div class="news-category-block">
                            <a href="#" class="category-block-link">
                                Lifestyle,
                            </a>

                            <a href="#" class="category-block-link">
                                Clothing Donation
                            </a>
                        </div>
                    </div>

                    <div class="news-block-info">
                        <div class="d-flex mt-2">
                            <div class="news-block-date">
                                <p>
                                    <i class="bi-calendar4 custom-icon me-1"></i>
                                    October 12, 2036
                                </p>
                            </div>
                        </div>

                        <div class="news-block-title mb-2">
                            <h4><a href="news-detail.html" class="news-block-title-link">Clothing donation to urban area</a></h4>
                        </div>

                        <div class="news-block-body">
                            <p>Lorem Ipsum dolor sit amet, consectetur adipsicing kengan omeg kohm tokito Professional charity theme based on Bootstrap</p>
                        </div>
                    </div>
                </div>

                <div class="news-block mt-3">
                    <div class="news-block-top">
                        <a href="news-detail.html">
                            <img src="{{ Vite::asset('resources/images/news/medium-shot-people-collecting-foodstuff.jpg') }}" class="news-image img-fluid" alt="">
                        </a>

                        <div class="news-category-block">
                            <a href="#" class="category-block-link">
                                Food,
                            </a>

                            <a href="#" class="category-block-link">
                                Donation,
                            </a>

                            <a href="#" class="category-block-link">
                                Caring
                            </a>
                        </div>
                    </div>

                    <div class="news-block-info">
                        <div class="d-flex mt-2">
                            <div class="news-block-date">
                                <p>
                                    <i class="bi-calendar4 custom-icon me-1"></i>
                                    October 20, 2036
                                </p>
                            </div>
                        </div>

                        <div class="news-block-title mb-2">
                            <h4><a href="news-detail.html" class="news-block-title-link">Food donation area</a></h4>
                        </div>

                        <div class="news-block-body">
                            <p>Sed leo nisl, posuere at molestie ac, suscipit auctor mauris. Etiam quis metus elementum, tempor risus vel, condimentum orci</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-12 mx-auto">
{{--                <form class="custom-form search-form" action="#" method="get" role="form">--}}
{{--                    <input name="search" type="search" class="form-control" id="search" placeholder="Search" aria-label="Search">--}}

{{--                    <button type="submit" class="form-control">--}}
{{--                        <i class="bi-search"></i>--}}
{{--                    </button>--}}
{{--                </form>--}}

               @include('partial.recent-posts')

                <div class="news-block news-block-two-col d-flex mt-4">
                    <div class="news-block-two-col-image-wrap">
                        <a href="news-detail.html">
                            <img src="{{ Vite::asset('resources/images/news/close-up-happy-people-working-together.jpg') }}" class="news-image img-fluid" alt="">
                        </a>
                    </div>

                    <div class="news-block-two-col-info">
                        <div class="news-block-title mb-2">
                            <h6><a href="news-detail.html" class="news-block-title-link">Volunteering Clean</a></h6>
                        </div>

                        <div class="news-block-date">
                            <p>
                                <i class="bi-calendar4 custom-icon me-1"></i>
                                October 24, 2036
                            </p>
                        </div>
                    </div>
                </div>

{{--                <div class="category-block d-flex flex-column">--}}
{{--                    <h5 class="mb-3">Categories</h5>--}}

{{--                    <a href="#" class="category-block-link">--}}
{{--                        Drinking water--}}
{{--                        <span class="badge">20</span>--}}
{{--                    </a>--}}

{{--                    <a href="#" class="category-block-link">--}}
{{--                        Food Donation--}}
{{--                        <span class="badge">30</span>--}}
{{--                    </a>--}}

{{--                    <a href="#" class="category-block-link">--}}
{{--                        Children Education--}}
{{--                        <span class="badge">10</span>--}}
{{--                    </a>--}}

{{--                    <a href="#" class="category-block-link">--}}
{{--                        Poverty Development--}}
{{--                        <span class="badge">15</span>--}}
{{--                    </a>--}}

{{--                    <a href="#" class="category-block-link">--}}
{{--                        Clothing Donation--}}
{{--                        <span class="badge">20</span>--}}
{{--                    </a>--}}
{{--                </div>--}}

{{--                <div class="tags-block">--}}
{{--                    <h5 class="mb-3">Tags</h5>--}}

{{--                    <a href="#" class="tags-block-link">--}}
{{--                        Donation--}}
{{--                    </a>--}}

{{--                    <a href="#" class="tags-block-link">--}}
{{--                        Clothing--}}
{{--                    </a>--}}

{{--                    <a href="#" class="tags-block-link">--}}
{{--                        Food--}}
{{--                    </a>--}}

{{--                    <a href="#" class="tags-block-link">--}}
{{--                        Children--}}
{{--                    </a>--}}

{{--                    <a href="#" class="tags-block-link">--}}
{{--                        Education--}}
{{--                    </a>--}}

{{--                    <a href="#" class="tags-block-link">--}}
{{--                        Poverty--}}
{{--                    </a>--}}

{{--                    <a href="#" class="tags-block-link">--}}
{{--                        Clean Water--}}
{{--                    </a>--}}
{{--                </div>--}}

{{--                <form class="custom-form subscribe-form" action="#" method="get" role="form">--}}
{{--                    <h5 class="mb-4">Newsletter Form</h5>--}}

{{--                    <input type="email" name="subscribe-email" id="subscribe-email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Email Address" required>--}}

{{--                    <div class="col-lg-12 col-12">--}}
{{--                        <button type="submit" class="form-control">Subscribe</button>--}}
{{--                    </div>--}}
{{--                </form>--}}
            </div>

        </div>
    </div>
</section>

resources/views/partial/main-slider.blade.php
<section class="hero-section hero-section-full-height">
    <div class="container-fluid">
        <div class="row">

            <div class="col-lg-12 col-12 p-0">
                <div id="hero-slide" class="carousel carousel-fade slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        @if($sliders->isEmpty())
                        <div class="carousel-item active">
                            <img src="{{ Vite::asset('resources/images/slide/volunteer-helping-with-donation-box.jpg') }}" class="carousel-image img-fluid" alt="...">

                            <div class="carousel-caption d-flex flex-column justify-content-end">
                                <h1>Default slider</h1>
                                <p>Professional approach to charity</p>
                            </div>
                        </div>
                        @else
                            @foreach($sliders as $slider)
                                <div class="carousel-item active">
                                    <img src="{{ Voyager::image($slider->image) }}" class="carousel-image img-fluid" alt="...">
                                    <div class="carousel-caption d-flex flex-column justify-content-end">
                                        <h1>{{ $slider->getTranslatedAttribute('title', App::getLocale(), 'fallbackLocale') }}</h1>
                                        <p>{{ $slider->getTranslatedAttribute('subtitle', App::getLocale(), 'fallbackLocale') }}</p>
                                    </div>
                                </div>
                            @endforeach
                        @endif
                    </div>

                    <button class="carousel-control-prev" type="button" data-bs-target="#hero-slide" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>

                    <button class="carousel-control-next" type="button" data-bs-target="#hero-slide" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>

        </div>
    </div>
</section>

resources/views/partial/recent-posts.blade.php
<h5 class="mb-3">{{ __('custom.recent_events') }}</h5>
@foreach ($recentEvents as $event)
    <div class="news-block news-block-two-col d-flex mt-4">
        <div class="news-block-two-col-image-wrap">
            <a href="{{ route('events.show', $event) }}">
                @if($event->image)
                    <img src="{{ Voyager::image($event->image) }}" class="news-image img-fluid" alt="">
                @else
                    <img src="{{ asset('/template/images/news/medium-shot-volunteers-with-clothing-donations.jpg') }}" class="news-image img-fluid" alt="">
                @endif
            </a>
        </div>

        <div class="news-block-two-col-info">
            <div class="news-block-title mb-2">
                <h6>
                    <a href="{{ route('events.show', $event ) }}" class="news-block-title-link">
                        {{ $event->getTranslatedAttribute('title', App::getLocale(), 'fallbackLocale') }}
                    </a>
                </h6>
            </div>

            <div class="news-block-date">
                <p>
                    <i class="bi-calendar4 custom-icon me-1"></i>
                    {{ $event->event_start }}
                </p>
            </div>
        </div>
    </div>
@endforeach

resources/views/partial/testimonial-block.blade.php
<section class="testimonial-section section-padding section-bg">
    <div class="container">
        <div class="row">

            <div class="col-lg-8 col-12 mx-auto">
{{--                <h2 class="mb-lg-3">Happy Customers</h2>--}}

                <div id="testimonial-carousel" class="carousel carousel-fade slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        @foreach(setting('quotes') as $quote)
                            <div class="carousel-item active">
                                <div class="carousel-caption">
                                    <h4 class="carousel-title">{{ $quote }}</h4>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

resources/views/partial/topnavbar.blade.php
<nav class="navbar navbar-expand-lg bg-light shadow-lg">
    <div class="container">
        <a class="navbar-brand" href="{{ route('index') }}">
            @if(Voyager::image(setting('site.logo')))
                <img src="{{ Voyager::image(setting('site.logo')) }}" class="logo img-fluid" alt="Kind Heart Charity">
            @else
                <img src="{{ asset('/template/images/logo.png') }}" class="logo img-fluid" alt="Kind Heart Charity">
            @endif
            <span>
                @if(env('APP_DEMO'))
                    {{ __('demo.main_title') }}
                @else
                    {{ __('settings.main_title') }}
                @endif
{{--                <small>{{ __('settings.main_sub_title') }}</small>--}}
            </span>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('index') }}">{{ __('custom.home') }}</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('about') }}">{{ __('custom.about') }}</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link smoothscroll" href="{{ route('index') }}#section_2">{{ __('custom.upcoming_events') }}</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('events.index') }}">{{ __('custom.events') }}</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link smoothscroll" href="{{ route('index') }}#section_6">{{ __('custom.contact') }}</a>
                </li>

{{--                <li class="nav-item ms-3">--}}
{{--                    <a class="nav-link custom-btn custom-border-btn btn" href="donate.html">Donate</a>--}}
{{--                </li>--}}
            </ul>
        </div>
    </div>
</nav>

resources/views/partial/upcoming-events-block.blade.php
<section class="section-padding section-bg" id="section_2">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12 text-center mb-4">
                <h2>{{ __('custom.upcoming_events') }}</h2>
            </div>

            @if(count($events) > 0)
                @foreach($events as $event)

                <div class="col-lg-4 col-md-6 col-12 mb-4 mb-lg-0">
                    <div class="custom-block-wrap">
                        @if($event->image)
                            <img src="{{ Voyager::image($event->image) }}" class="custom-block-image img-fluid" alt="">
                        @else
                            <img src="{{ asset('/template/images/news/medium-shot-volunteers-with-clothing-donations.jpg') }}" class="custom-block-image img-fluid" alt="">
                        @endif
                        <div class="custom-block">
                            <div class="custom-block-body">
                                <h5 class="mb-3">{{ $event->getTranslatedAttribute('title', App::getLocale(), 'fallbackLocale') }}</h5>
                                <p>{{ $event->getTranslatedAttribute('excerpt', App::getLocale(), 'fallbackLocale') }}</p>
                                <div class="progress mt-4">
                                    <div class="progress-bar w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <div class="my-2">
                                    <p class="mb-0">
                                        <strong>{{ __('custom.start') }}:</strong>
                                        {{ date('Y-m-d H:i', strtotime($event->event_start)) }}
                                    </p>
                                    @if($event->event_end)
                                    <p class="mb-0">
                                        <strong>{{ __('custom.end') }}:&nbsp;&nbsp;</strong>
                                        {{ date('Y-m-d H:i', strtotime($event->event_end)) }}
                                    </p>
                                    @endif
                                </div>
                                @if($event->age_from || $event->age_to)
                                <div class="my-2">
                                    <p class="mb-0">
                                        <strong>{{ __('custom.age_restrictions') }}:</strong>
                                        {{ $event->age_from . ' - ' }}{{ $event->age_to }}
                                    </p>
                                </div>
                                @endif
                            </div>
                            <a href="{{ route('events.show',$event) }}" class="custom-btn btn">{{ __('custom.see_more') }}</a>
                        </div>
                    </div>
                </div>

                @endforeach
            @else
                {{ __('custom.no_events') }}
            @endif

        </div>
    </div>
</section>