routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use TCG\Voyager\Facades\Voyager;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\Voyager\ParticipantController;
use App\Http\Controllers\ExportController;
use App\Http\Controllers\ChildrenController;
//use App\Http\Controllers\Voyager\VoyagerSettingsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group([
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function() {
        Route::get('/', [PageController::class,'index'])->name('index');
        Route::get('/about-us', [PageController::class,'about'])->name('about');
        Route::get('/release', [PageController::class,'release'])->name('release');
        Route::resource('/posts', PostController::class)
            ->only(['index', 'show'])
            ->names('posts');
        Route::resource('/events', EventController::class)
            ->only(['index', 'show'])
            ->names('events');
        Route::post('/add-message', [MessageController::class, 'addMessage'])
            ->name('addMessage');
});

Route::post('/event-participate/{event}', [EventController::class, 'onParticipate'])->middleware('auth')->name('eventParticipate');

// Panel pages
Route::group(['prefix' => 'panel'], function () {
    Voyager::routes();
    Route::get('/events/{event}/participants',[ParticipantController::class,'indexByEvent'])->name('voyager.participants.indexByEvent');
    Route::get('/to-accept-participant/{participant}',[ParticipantController::class,'toAccept'])->name('voyager.participants.toAccept');
    Route::get('/to-reject-participant/{participant}',[ParticipantController::class,'toReject'])->name('voyager.participants.toReject');
    Route::get('/to-draft-participant/{participant}',[ParticipantController::class,'toDraft'])->name('voyager.participants.toDraft');
    Route::get('/to-invite-participant/{participant}',[ParticipantController::class,'toInvite'])->name('voyager.participants.toInvite');
    Route::post('/to-invite-participant-bulk/{event}',[ParticipantController::class,'toInviteBulk'])->name('voyager.participants.toInviteBulk');
    Route::get('/to-service-participant/{participant}',[ParticipantController::class,'toService'])->name('voyager.participants.toService');

    Route::get('/events/{event}/participants/export/', [ExportController::class, 'exportParticipantsEvent'])->name('export.participants.event');
});

// Profile pages
Route::get('/dashboard', [ProfileController::class, 'show'])->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::patch('/update-contact-info', [ProfileController::class, 'updateContactInfo'])->name('profile.updateContactInfo');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('/children', ChildrenController::class)->only(['index','store']);
    Route::patch('/children/{children}', [ChildrenController::class, 'update'])->name('children.update');
    Route::delete('/children/{children}', [ChildrenController::class, 'destroy'])->name('children.destroy');

});

require __DIR__.'/auth.php';

resources/views/layouts/alert.blade.php
@if (\Session::has('success'))
    <div class="my-2 offset-2 col-8 alert alert-success alert-dismissible fade show" role="alert">
        {!! \Session::get('success') !!}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@elseif(\Session::has('warning'))
    <div class="my-2 offset-2 col-8 text-center alert alert-warning alert-dismissible fade show" role="alert">
        {!! \Session::get('warning') !!}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@elseif(\Session::has('error'))
    <div class="my-2 offset-2 col-8 text-center alert alert-error alert-dismissible fade show" role="alert">
        {!! \Session::get('error') !!}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'HADAS') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap">

        @if(env('APP_ENV') === 'local')
            @vite(['resources/css/app.css', 'resources/js/app.js', 'resources/css/bootstrap.min.css'])
        @else
            <link rel="stylesheet" type="text/css" href="/build/assets/app.acc3b0d3.css">
            <link rel="stylesheet" type="text/css" href="/build/assets/bootstrap-icons.css">
        @endif
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">

    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            @if (isset($header))
                <header class="bg-white shadow">
                    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                        {{ $header }}
                    </div>
                </header>
            @endif

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
        <script src="/build/assets/bootstrap.min.js"></script>
        <script src="/build/assets/app.297ec3b5.js"></script>
    </body>
</html>

resources/views/layouts/application.blade.php
<!doctype html>
<html lang="{{ App::getLocale() }}"  theme="{{ setting('site.color_schema') ?: 'original' }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{ config('app.name', 'HADAS') }} - @yield('title')</title>
    <meta property="og:image" content="@yield('og:image')" />
    <meta property="og:description" content="@yield('og:description')" />
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap">

    @if(env('APP_ENV') === 'local')
        @vite(['resources/css/application.css', 'resources/js/application.js'])
    @else
        <link rel="stylesheet" type="text/css" href="/build/assets/bootstrap-icons.css">
        <link rel="stylesheet" type="text/css" href="/build/assets/application.c27ae35a.css">
    @endif
{{--    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@v3.0.0-rc.17/dist/cookieconsent.css">--}}

    <!-- Load Facebook SDK for JavaScript -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
</head>

<body id="section_1">

@include('partial.topbar')
@include('partial.topnavbar')

<main>
@section('content')

@show
</main>
@include('partial.footer')
<script
    src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
    crossorigin="anonymous"
></script>

@if(env('APP_ENV') === 'public')
    <script src="/build/assets/jquery.min.js"></script>
    <script src="/build/assets/bootstrap.min.js"></script>
    <script src="/build/assets/jquery.sticky.js"></script>
    <script src="/build/assets/click-scroll.js"></script>
    <script src="/build/assets/counter.js"></script>
    <script src="/build/assets/custom.js"></script>
@endif
</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'HADAS') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap">
        {{--    TODO: temp solution--}}
                @if(env('APP_ENV') === 'local')
                    @vite(['resources/css/app.css', 'resources/js/app.js'])
                @else
                    <link rel="stylesheet" type="text/css" href="/build/assets/app.acc3b0d3.css">
                    <link rel="stylesheet" type="text/css" href="/build/assets/bootstrap-icons.css">
                    <script type="text/javascript" src="/build/assets/bootstrap.32611946.js"></script>
                    <script type="text/javascript" src="/build/assets/app.297ec3b5.js"></script>
                @endif
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-9 w-auto fill-current text-gray-800" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('index')">
                        {{ __('Home') }}
                    </x-nav-link>
                </div>
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>

            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition ease-in-out duration-150">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <x-dropdown-link :href="route('profile.edit')">
                            {{ __('Profile') }}
                        </x-dropdown-link>

                        <x-dropdown-link :href="route('children.index')">
                            {{ __('Children') }}
                        </x-dropdown-link>

                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <x-responsive-nav-link :href="route('profile.edit')">
                    {{ __('Profile') }}
                </x-response-nav-link>

                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>